### ISSUE TITLE
Show time of last publish and number of recent downloads if unavailable

### ISSUE THREAD

**Issue by jgallen23** [sindresorhus/npm-name#11]
Would be nice to show if a package is still activity being developed and used. Might be a chance the user would give up the name.

**Comment by sholladay** [comment]
I built a module with some heuristics that tries to guess if the package name is worth going after.

https://github.com/sholladay/squatter

It doesn't currently print statistics. But I've been thinking about at least adding a `.score()` method to output a confidence level.

**Comment by sindresorhus** [comment]
The npms API provides a score: https://api-docs.npms.io/#api-Package-GetPackageInfo

It's based on a pretty good algorithm: https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md

**Comment by sindresorhus** [comment]
Closing in favor of handling this in the `squatter` module. When it's implemented there, PR welcome to support it here.
