### ISSUE TITLE
Flaky results, especially with `pinto`

### ISSUE THREAD

**Issue by citycide** [sindresorhus/npm-name#13]
[`pinto`](https://www.npmjs.com/package/pinto) - at time of writing - isn't take on npm. The results for this specific word are _super_ flaky though, and I don't know why. It fails about 80% of the time, returning `false` when it should obviously return `true` since it's available. There don't seem to be any errors.

You can run the below code in this [RunKit notebook](https://runkit.com/citycide/npm-name-flakiness).

```js
const isAvailable = require('npm-name')
const partition = require('lodash.partition')

const fetch = word => {
  const array = new Array(100).fill(word)
  return Promise.all(array.map(isAvailable))
    .then(names => partition(names, Boolean))
}

const test = async word => {
  const [avail, not] = await fetch(word)
  console.log(`${word}: ${avail.length} / ${not.length}`)
}

await test('pinto')
```

**Comment by sindresorhus** [comment]
The problem is in the registry. Sometimes it returns 404 and other times it successfully returns:

```js
{ _id: 'pinto',
  _rev: '2-5230289d139183623495b77ae1c508a4',
  name: 'pinto',
  time:
   { modified: '2017-10-11T23:10:03.171Z',
     created: '2017-10-11T13:12:55.599Z',
     '0.1.0': '2017-10-11T13:12:55.599Z',
     unpublished:
      { name: 'mwjaworski',
        time: '2017-10-11T23:10:03.171Z',
        tags: [Object],
        maintainers: [Array],
        versions: [Array] } },
  _attachments: {} }
```

Can you open an issue about this on https://github.com/npm/registry/issues? It should always return the same thing. Either 404 or the above result.

On our side, we should also check whether a package has the `unpublished` property.

**Comment by citycide** [comment]
@sindresorhus done

**Comment by sindresorhus** [comment]
If this is still an issue, it needs to be re-reported to https://npm.community/c/bugs
