### ISSUE TITLE
Support for organization

### ISSUE THREAD

**Issue by rmariuzzo** [sindresorhus/npm-name#14]
NPM has organization which work along with the scoped package features. Therefore, I think it would be handy to do:

```shell
npm-name @elemental
```

The `@` to detect an org instead of a package name.

**Comment by sindresorhus** [comment]
Good idea. PR welcome :)

**Comment by rmariuzzo** [comment]
Unfortunately, the NPM registry doesn't provide an endpoint to detect orgs. However, I was able to add support for usage as: `npm-name @sindresorhus/is`. Do you think this would be worth a PR? I have already done this at 32606b8b7aec7d0631988089c99a82b0c6bf349f.

**Comment by sindresorhus** [comment]
@rmariuzzo You could maybe do a HEAD request to https://www.npmjs.com/org/ava where `ava` is the org name to check. That will only work for public orgs though.

Could also potentially do the same form request as done here: https://www.npmjs.com/org/create (Try creating an org named `ava` and you'll see they notify that it already exists.

**Comment by sidoshi** [comment]
Can I work on this?

**Comment by sindresorhus** [comment]
Go ahead :)
