### ISSUE TITLE
Dependency `electron` not found (in `got`) when used in Next project

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/npm-name#16]
Ran into an interesting issue using this module in a `nextjs` project.

```bash
This dependency was not found:  
* electron in ./node_modules/npm-name/node_modules/got/index.js  
To install it, you can run: npm install --save electron
```

I don't want to introduce electron to the project obviously, and looking through the [source of `got`](https://github.com/sindresorhus/got/blob/master/index.js#L90), I'm not sure why it's being required.

Any insight into this?

**Comment by sindresorhus** [comment]
The `require` is behind a conditional, so this is an issue with `nextjs`.

**Comment by lacymorrow** [comment]
Seems to be an issue with Webpack aggressively bundling dependencies.
