### ISSUE TITLE
Support for scoped packages

### ISSUE THREAD

**Issue by clemtrek** [sindresorhus/npm-name#17]
I was just searching names for my project when I saw that this package does not support scoped packages.

Check https://runkit.com/embed/mzsivagq3l35 for a demo.

**Comment by sindresorhus** [comment]
@rmariuzzo Would you be able to submit your changes for this?

**Comment by rmariuzzo** [comment]
Hey @sindresorhus! I haven't be able to submit changes, however @clemtrek seems like he did some work.
