### ISSUE TITLE
Allow overriding the registry URL

### ISSUE THREAD

**Issue by itaisteinherz** [sindresorhus/npm-name#31]
In some cases (e.g. in [np](https://github.com/sindresorhus/np/blob/d10ffcf9919c321c008d5aacc79805381745df67/source/cli.js#L76) - see sindresorhus/np#350 and sindresorhus/np#317) you want to resolve a package name for a given registry that wasn't configured to be the user's default registry. I think that `npm-name` should still use the registry URL returned by [`registry-url`](https://github.com/sindresorhus/registry-url) as the default one, but also accept an optional registry URL as the second argument, i.e. `npmName(name, [registryUrl])` and `npmName.many(names, [registryUrl])`.

// cc @weekens @jdziat

**Comment by sindresorhus** [comment]
Not a big fan of this idea. I would prefer it to be fully automatic or if that's not possible, for `np` just to skip the name checking.

**Comment by sindresorhus** [comment]
Also note, that `npm-name` supports private registries now: https://github.com/sindresorhus/npm-name/commit/c4e850b42a14da5348b2793ee4add4cd77e772da

**Comment by itaisteinherz** [comment]
> Also note that `npm-name` supports private registries now

It does, but it won't be able to correctly check the name of a private package in case the package is a private package which is published to a custom private registry, while the currently configured npm registry is a different one (probably https://registry.npmjs.org in the issues I've mentioned above).

**Comment by sindresorhus** [comment]
Since I accepted https://github.com/sindresorhus/package-json/commit/53c40f268d16b72de11a4615461dff827b1a0b28, I guess I should accept this too, but it too should come with a big warning about when and when *not* to use it.

**Comment by itaisteinherz** [comment]
I'll work on a PR to add this 👌🏻
