### ISSUE TITLE
automatically check both organisation and package names

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/npm-name#39]
I have a request,
whenever I check packages, I'd like to consider if I'd want to use the package name, or the organisation name.

I currently always do `npm-name some-pkg @some-pkg`

I'd love for this cli to automatically check both the package and the organisation at once, without having to type it twice! ;)

**Comment by sindresorhus** [comment]
I think that's too obscure of an use-case and not really something I would encourage. You shouldn't create a organization each time you make a package. You can solve this yourself with a shell function:

```shell
npm-name() { npm-name "$0" "@$0" }
```
